# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: It's all about Software
# email: draghuram at gmail dot com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog about all things related to Software. In particular, 
  I am going to write about my opinions and preferences in the way code
  is developed, tested, and documented. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://draghuram.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  draghuram

# Build settings
markdown: kramdown
